<?php
namespace kordar\ace\web\widgets\search;

use yii\base\Widget;
use yii\helpers\Html;

class DropDownSearch extends Widget
{
    public $id = '';

    public $name = '';

    /**
     * @var \yii\base\Model
     */
    public $model;

    /**
     * @var array
     */
    public $items = [];

    public $inputOption = ['size' => 35];

    public function beforeRun()
    {
        $class = get_class($this->model);
        $this->name = basename(str_replace('\\', '/', $class));

        $this->id = empty($this->id) ? substr(md5(serialize($this->items)), 8, 16) : $this->id;

        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $list = [];

        $firstKey = '';

        foreach ($this->items as $key => $item) {
            $n = $this->name . '[' . $item . ']';
            if ($key == 0) {
                $firstKey = $n;
            }
            $list[$n] = $this->model->getAttributeLabel($item);
        }

        $request = \Yii::$app->request;
        $name = $request->get($this->id, $firstKey);

        $selection = Html::dropDownList($this->id, $name, $list, ['class'=>'form-control']);

        $this->inputOption['class'] = 'form-control';
        $this->inputOption['id'] = $this->id;

        $result = [];
        preg_match_all("/(?:\[)(.*)(?:\])/i", $name, $result);
        $_name = $result[1][0];

        $params = $request->get($this->name);
        $value = empty($params[$_name]) ? '' : $params[$_name];

        $input = Html::input('text', $name, $value, $this->inputOption);

        echo Html::tag('div', "{$selection} \n {$input}",  ['class'=>'form-group field-' . $this->id]);

        $this->view->registerJs("\$('select[name=\"{$this->id}\"]').change(function() {\$('#{$this->id}').prop('name', \$(this).val());});");
    }
}