<?php
namespace kordar\ace\web\widgets\upload;

use kordar\ace\web\assets\UploadAsset;
use kordar\ace\web\helper\WidgetHelper;
use yii\helpers\Url;
use yii\widgets\InputWidget;
use yii\helpers\Html;

class Well extends InputWidget
{
    /**
     * @var string
     * Url
     */
    public $url = '';

    /**
     * @var string
     * Title
     */
    public $title = 'Title';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        UploadAsset::register($this->view);
        echo Html::activeHiddenInput($this->model, $this->attribute, ['id'=>'kordar-upload-hidden'])
            . Html::activeInput('file', $this->model, $this->attribute);
    }

    public function run()
    {
        $url = $this->url ? : Url::to(['upload']);
        $js = WidgetHelper::inputJs($this->options['id'], [
                    "style" => 'well',
               "btn_choose" => \Yii::t('ace.upload', 'Drop files here or click to choose'),
               "btn_change" => null,
                  "no_icon" => 'ace-icon fa fa-cloud-upload',
                "droppable" => true,
                'thumbnail' => 'small',
            "before_remove" => 'function() {
                                    $(\'#kordar-upload-hidden\').val(\'\');
                                    return true;
                                }'
            //,icon_remove:null//set null, to hide remove/reset button
            //,before_change:function(files, dropped) {
            //Check an example below
            //or examples/file-upload.html
            //return true;
            //},
            // preview_error : function(filename, error_code) {
                //name of the file that failed
                //error_code values
                //1 = 'FILE_LOAD_FAILED',
                //2 = 'IMAGE_LOAD_FAILED',
                //3 = 'THUMBNAIL_FAILED'
                //alert(error_code);
            // }
        ], WidgetHelper::callbackJs($this->options['id'], $url, 'function(json) {
                if (json.status === 200) {
                    $(\'#kordar-upload-hidden\').val(json.path);
                } else {
                    bootbox.alert(json.msg);
                }
            }', 'function() {return $(\'#kordar-upload-hidden\').val();}'));
        $this->view->registerJs($js);
        $attribute = $this->attribute;
        $showJs = WidgetHelper::showWellJs($this->options['id'], $this->model->$attribute);
        if ($showJs !== null) {
            $this->view->registerJs($showJs);
        }
    }
}